### ISSUE TITLE
关于单张图像测试demo的问题，以及如何获取单张图像的不确定性

### ISSUE THREAD

**Issue by gen0924** [yuantn/MI-AOD#22]
![image](https://user-images.githubusercontent.com/19650201/122898645-a191ed00-d37d-11eb-998d-9e3c9b20ff44.png)
您好，在进行单张图像测试时，出现这样的错误，方便告知是什么原因嘛？另外，如果我是想获取单张图像的不确定性呢，是不是需要调整推理时result = model(return_loss=False, rescale=True, **data)为y_head_f_1, y_head_f_2, y_head_cls = model(return_loss=False, rescale=True, return_box=return_box, **data)，之后再基于calculate_uncertainty函数做修改和调整！给你的工作和生活带来不便，还请谅解，期待您的回复！谢谢

**Comment by yuantn** [comment]
你好，你需要的功能已更新，请参见 [此处](../blob/master/README_cn.md#训练和测试)。

这个错误出现的原因是因为我之前为了和论文中变量相对应，曾经修改了读取图像时的一些变量。因此需要像 `mmdet/apis/test.py` 中一样做出一些改动。关于单张图像的不确定性，是如你所说的那样，且在 `mmdet/apis/inference.py` 中已经加入该新功能。有问题欢迎提问，不用那么客气 😄 

---

Hi, the function you need has been updated. Please refer to [here](../#train-and-test).

The error occurs because I have modified some variables when reading images in order to make the code correspond to the variables in the paper. Therefore, something need to be modified as in `mmdet/apis/test.py`. For the uncertainty of a single image, it is as you said. And this new feature has been added in `mmdet/apis/inference.py`. If you have any questions, just feel free to ask, don’t be so cautious 😄
