### ISSUE TITLE
Trained model on COCO dataset

### ISSUE THREAD

**Issue by xbsu** [yuantn/MI-AOD#50]
Hi, could you provide the trained model and training log on COCO dataset? 

Thanks a lot.

**Comment by yuantn** [comment]
Here is the training log on COCO dataset: [Google Drive](https://drive.google.com/file/d/1TDJSqNs6IH05hFerSNRGQIaTuTpo1A5J/view?usp=sharing) | [Baidu Drive (Extraction Code: as7h)](https://pan.baidu.com/s/1o5pemMzyrx3IAe6vd-foTA)

When training on the COCO dataset a year ago, we didn't save the model because its size was too large and took up too much storage space. But you can refer to the example output folder here ([Google Drive](https://drive.google.com/file/d/1awtj2EAanP_wCate4gcpzhEnSuHfSfDY/view?usp=sharing) | [Baidu Drive (Extraction Code: fudq)](https://pan.baidu.com/s/1dwKhTcLFl7ZzfEmqZxhBaw)), which provides the selected sample index in each active learning cycle.
