### ISSUE TITLE
请问下换成anchor free的网络可以用吗

### ISSUE THREAD

**Issue by nancy618618618** [yuantn/MI-AOD#58]
你好，请问下用anchor free centernet的检测网络可以用这个方法吗，谢谢

**Comment by yuantn** [comment]
Hello, this method will greatly improve the performance on the anchor-based detection model, because it takes the anchor-/instance-level uncertainty learning into account.

But for an anchor-free network like CenterNet, more modifications may be needed correspondingly, such as mapping the uncertainty in each anchor box to the uncertainty of a certain range spread from each center point, etc..

Future research will be considered.

---

你好，本方法对于基于锚框的检测模型会有较大的性能提升，因其考虑到了框级别的不确定的学习过程。

但对于像 CenterNet 这样的无锚框网络，可能需要相应地做出更多的改动，如考虑将每一个锚框内的不确定性映射为从每一个中心点扩散开的某个范围的不确定性等等。

我们后续会考虑在这方面的研究。
